package ai.javaclaw.agent.memory;

import java.time.Instant;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Spring Data JDBC entity that maps to the {@code SPRING_AI_CHAT_MEMORY} table.
 *
 * <p>The surrogate {@code id} column is auto-generated by the database
 * (PostgreSQL: {@code BIGINT GENERATED ALWAYS AS IDENTITY}; SQLite: {@code INTEGER PRIMARY KEY AUTOINCREMENT}).
 * New entries are created with {@code id = null} so Spring Data JDBC performs an INSERT
 * and reads the generated key back.
 *
 * <p>{@code content} is nullable — tool-call messages carry no text body.
 *
 * <p>{@code type} stores {@link org.springframework.ai.chat.messages.MessageType#name()}:
 * {@code USER}, {@code ASSISTANT}, {@code SYSTEM}, or {@code TOOL}.
 */
@Table("SPRING_AI_CHAT_MEMORY")
public record ChatMemoryEntry(
        /** Auto-generated surrogate PK. Null on creation; populated after save. */
        @Id Long id,
        /** FK to {@code conversations.id}. */
        @Column("conversation_id") String conversationId,
        /** Message text body; null for TOOL messages. */
        String content,
        /** {@link org.springframework.ai.chat.messages.MessageType#name()} value. */
        String type,
        /** Creation timestamp — used for deterministic ordering within a conversation. */
        @Column("created_at") Instant createdAt) {}
