package ai.javaclaw.users;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Full projection of the {@code users} table — used for authentication
 * and user management.
 */
@Table("users")
public record AppUser(
        @Id String id,
        @Column("username") String username,
        @Column("password_hash") String passwordHash,
        @Column("role") String role,
        @Column("active") boolean active) {

    /** Create a new user (id generated by DB). */
    public static AppUser create(String username, String passwordHash, String role) {
        return new AppUser(null, username, passwordHash, role, true);
    }
}
