package ai.javaclaw.agent.memory.adapter.jdbc;

import java.time.Instant;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Spring Data JDBC entity that maps to the {@code spring_ai_chat_memory} table.
 *
 * <p>One row per stored chat message. The layout is intentionally flat — no FK objects,
 * no nested aggregates — so Spring Data JDBC can batch-insert entries via
 * {@link ChatMemoryEntryJdbcRepository#saveAll(Iterable)} without aggregate-root juggling.
 *
 * <h2>Column semantics</h2>
 * <ul>
 *   <li>{@code id} — surrogate PK auto-generated by the database. PostgreSQL uses
 *       {@code BIGINT GENERATED ALWAYS AS IDENTITY}; SQLite uses
 *       {@code INTEGER PRIMARY KEY AUTOINCREMENT}. New entries are created with
 *       {@code id = null} so Spring Data JDBC performs an INSERT and reads the
 *       generated key back.
 *   <li>{@code conversationId} — logical FK to {@code conversations.id}. The actual
 *       constraint is owned by {@code javaclaw-core} migration V5; the memory module's
 *       own Flyway scripts intentionally omit it so tests can run without the full core
 *       schema on the classpath.
 *   <li>{@code content} — message text body. Nullable because {@code TOOL} messages
 *       carry no text (only tool-call metadata, which is not persisted here).
 *   <li>{@code type} — stores
 *       {@link org.springframework.ai.chat.messages.MessageType#name()}: one of
 *       {@code USER}, {@code ASSISTANT}, {@code SYSTEM}, {@code TOOL}. A CHECK constraint
 *       in the SQLite migration enforces this set; PostgreSQL relies on application-level
 *       validation.
 *   <li>{@code createdAt} — informational creation timestamp. Ordering of
 *       {@code findByConversationId} uses the surrogate {@code id}, not this field,
 *       because SQLite's second-level resolution would lose ordering within a batch.
 * </ul>
 *
 * @param id auto-generated surrogate PK; {@code null} on creation, populated after save
 * @param conversationId logical FK to {@code conversations.id}; must be non-null
 * @param content message text body; {@code null} for {@code TOOL} messages
 * @param type {@link org.springframework.ai.chat.messages.MessageType#name()} value
 * @param createdAt creation timestamp metadata; ordering is by surrogate {@code id}, not this field
 */
@Table("spring_ai_chat_memory")
public record ChatMemoryEntry(
        @Id Long id,
        @Column("conversation_id") String conversationId,
        String content,
        String type,
        @Column("created_at") Instant createdAt) {}
