package ai.javaclaw.agent.event;

public enum EventKind {
    TURN_START,
    TURN_END,
    LLM_REQUEST,
    LLM_RESPONSE,
    LLM_DELTA,
    TOOL_EXEC_START,
    TOOL_EXEC_END,
    TOOL_EXEC_DENIED,
    TASK_CREATED,
    TASK_STATUS_CHANGE,
    TASK_CANCELLED,
    SUBTASK_SPAWN,
    SUBTASK_END,
    SUBTASK_RESULT_INJECTED,
    APPROVAL_REQUESTED,
    APPROVAL_RECEIVED,
    PROGRESS_UPDATE,
    ERROR
}
