plugins {
    id 'java-library'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.modulith:spring-modulith-starter-core'
    implementation 'org.jobrunr:jobrunr-spring-boot-4-starter:8.5.1'
    implementation 'org.apache.commons:commons-lang3'

    // No idea?
    runtimeOnly 'io.netty:netty-resolver-dns-native-macos:4.2.10.Final'

    implementation 'org.springframework.ai:spring-ai-client-chat'
    implementation 'org.springframework.ai:spring-ai-starter-model-chat-memory-repository-jdbc'
    implementation 'org.springframework.ai:spring-ai-starter-mcp-client'

    implementation 'org.springaicommunity:spring-ai-agent-utils:0.6.0-SNAPSHOT'

    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jdbc-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.awaitility:awaitility'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers-postgresql'
    testImplementation 'org.springframework.boot:spring-boot-flyway'
    testImplementation 'org.flywaydb:flyway-database-postgresql'
    testRuntimeOnly 'org.postgresql:postgresql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
