package ai.javaclaw.agent.config;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;
import org.springframework.lang.Nullable;

/**
 * Per-role agent configuration: which model to use, thinking settings, fallback chain.
 * Stored in {@code role_agent_config} table (V36 migration).
 *
 * <p>If {@code modelId} is null, the system default model is used for that role.
 */
@Table("role_agent_config")
public record RoleAgentConfig(
        @Id String id,
        @Column("role") String role,
        @Nullable @Column("model_id") String modelId,
        @Column("thinking_enabled") boolean thinkingEnabled,
        @Column("thinking_budget") int thinkingBudget,
        @Nullable @Column("fallback_models") String fallbackModels,
        @Column("max_context_tokens") int maxContextTokens) {

    /** Create a new config (id generated by DB). */
    public static RoleAgentConfig create(
            String role,
            @Nullable String modelId,
            boolean thinkingEnabled,
            int thinkingBudget,
            @Nullable String fallbackModels,
            int maxContextTokens) {
        return new RoleAgentConfig(
                null, role, modelId, thinkingEnabled, thinkingBudget, fallbackModels, maxContextTokens);
    }

    /** Returns fallback models as a list (comma-separated in DB). */
    public java.util.List<String> fallbackModelList() {
        if (fallbackModels == null || fallbackModels.isBlank()) {
            return java.util.List.of();
        }
        return java.util.Arrays.stream(fallbackModels.split(","))
                .map(String::trim)
                .filter(s -> !s.isEmpty())
                .toList();
    }

    /** Returns a copy with updated fields. */
    public RoleAgentConfig withModelId(@Nullable String modelId) {
        return new RoleAgentConfig(
                id, role, modelId, thinkingEnabled, thinkingBudget, fallbackModels, maxContextTokens);
    }

    public RoleAgentConfig withThinking(boolean enabled, int budget) {
        return new RoleAgentConfig(id, role, modelId, enabled, budget, fallbackModels, maxContextTokens);
    }

    public RoleAgentConfig withFallbackModels(@Nullable String fallbackModels) {
        return new RoleAgentConfig(
                id, role, modelId, thinkingEnabled, thinkingBudget, fallbackModels, maxContextTokens);
    }

    public RoleAgentConfig withMaxContextTokens(int maxContextTokens) {
        return new RoleAgentConfig(
                id, role, modelId, thinkingEnabled, thinkingBudget, fallbackModels, maxContextTokens);
    }
}
