package ai.javaclaw.cli;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * Standalone CLI tool for generating JavaClaw deployment configuration files.
 * Does not require Spring context — can be run independently.
 *
 * Usage: java -cp javaclaw-app.jar ai.javaclaw.cli.ConfigGenerator [output-dir] [--force]
 */
public class ConfigGenerator {

    private final Path outputDir;
    private final boolean force;

    public ConfigGenerator(Path outputDir, boolean force) {
        this.outputDir = outputDir;
        this.force = force;
    }

    public static void main(String[] args) {
        Path dir = Path.of(".");
        boolean force = false;

        for (String arg : args) {
            if ("--force".equals(arg)) {
                force = true;
            } else if ("--help".equals(arg) || "-h".equals(arg)) {
                printUsage();
                return;
            } else if (!arg.startsWith("-")) {
                dir = Path.of(arg);
            }
        }

        var generator = new ConfigGenerator(dir, force);
        List<String> generated = generator.generateAll();

        if (generated.isEmpty()) {
            System.out.println("No files generated (all already exist). Use --force to overwrite.");
        } else {
            System.out.println("Generated " + generated.size() + " file(s):");
            generated.forEach(f -> System.out.println("  - " + f));
        }
    }

    static void printUsage() {
        System.out.println("JavaClaw Config Generator");
        System.out.println();
        System.out.println("Usage: java -cp javaclaw-app.jar ai.javaclaw.cli.ConfigGenerator [output-dir] [--force]");
        System.out.println();
        System.out.println("Options:");
        System.out.println("  output-dir   Directory for generated files (default: current directory)");
        System.out.println("  --force      Overwrite existing files");
        System.out.println("  --help, -h   Show this help");
        System.out.println();
        System.out.println("Generated files:");
        System.out.println("  application.yaml    Spring Boot configuration");
        System.out.println("  docker-compose.yml  Docker Compose stack (app + postgres)");
        System.out.println("  .env.example        Environment variables template");
    }

    public List<String> generateAll() {
        List<String> generated = new ArrayList<>();

        if (writeFile("application.yaml", generateApplicationYaml())) {
            generated.add("application.yaml");
        }
        if (writeFile("docker-compose.yml", generateDockerCompose())) {
            generated.add("docker-compose.yml");
        }
        if (writeFile(".env.example", generateEnvExample())) {
            generated.add(".env.example");
        }

        return generated;
    }

    boolean writeFile(String filename, String content) {
        Path target = outputDir.resolve(filename);
        if (!force && Files.exists(target)) {
            return false;
        }
        try {
            Files.createDirectories(outputDir);
            Files.writeString(target, content);
            return true;
        } catch (IOException e) {
            System.err.println("Error writing " + filename + ": " + e.getMessage());
            return false;
        }
    }

    public String generateApplicationYaml() {
        return """
                # JavaClaw Application Configuration
                # Generated by ConfigGenerator — customize values for your deployment

                server:
                  port: ${PORT:8080}
                  shutdown: graceful

                spring:
                  application:
                    name: javaclaw
                  lifecycle:
                    timeout-per-shutdown-phase: 30s
                  threads:
                    virtual:
                      enabled: true
                  datasource:
                    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:javaclaw}
                    username: ${DB_USERNAME:javaclaw}
                    password: ${DB_PASSWORD:javaclaw}
                  flyway:
                    enabled: true
                    locations: classpath:db/migration/{vendor}
                  ai:
                    openai:
                      api-key: ${OPENROUTER_API_KEY:}
                      base-url: ${OPENAI_BASE_URL:https://openrouter.ai/api/v1}
                      chat:
                        options:
                          model: ${CHAT_MODEL:anthropic/claude-sonnet-4-20250514}

                management:
                  endpoints:
                    web:
                      exposure:
                        include: health,info,metrics
                  endpoint:
                    health:
                      probes:
                        enabled: true

                agent:
                  onboarding:
                    completed: true
                  workspace:
                    dir: ${WORKSPACE_DIR:.}

                javaclaw:
                  security:
                    users:
                      - username: admin
                        password: ${ADMIN_PASSWORD:admin}
                        role: ADMIN
                      - username: user
                        password: ${USER_PASSWORD:user}
                        role: USER
                  chat:
                    thinking:
                      enabled: ${THINKING_ENABLED:false}
                      budget-tokens: ${THINKING_BUDGET_TOKENS:10000}
                    fallback:
                      enabled: ${MODEL_FALLBACK_ENABLED:false}
                      models: ${MODEL_FALLBACK_MODELS:}
                      max-retries-per-model: ${MODEL_FALLBACK_MAX_RETRIES:2}
                    tool-deny:
                      enabled: true
                      global-patterns:
                        - "rm\\\\s+-rf\\\\s+/"
                        - "DROP\\\\s+TABLE"
                        - "TRUNCATE\\\\s+TABLE"
                        - "chmod\\\\s+777"
                        - "curl.*\\\\|\\\\s*sh"

                jobrunr:
                  background-job-server:
                    enabled: true
                  dashboard:
                    enabled: false
                """;
    }

    public String generateDockerCompose() {
        return """
                # JavaClaw Docker Compose Stack
                # Generated by ConfigGenerator
                #
                # Usage:
                #   cp .env.example .env
                #   # Edit .env with your API keys and passwords
                #   docker compose up -d

                services:
                  app:
                    image: javaclaw:latest
                    build: .
                    ports:
                      - "${PORT:-8080}:8080"
                    environment:
                      - DB_HOST=postgres
                      - DB_PORT=5432
                      - DB_NAME=${DB_NAME:-javaclaw}
                      - DB_USERNAME=${DB_USERNAME:-javaclaw}
                      - DB_PASSWORD=${DB_PASSWORD:-javaclaw}
                      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
                      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
                      - USER_PASSWORD=${USER_PASSWORD:-user}
                      - CHAT_MODEL=${CHAT_MODEL:-anthropic/claude-sonnet-4-20250514}
                      - THINKING_ENABLED=${THINKING_ENABLED:-false}
                      - MODEL_FALLBACK_ENABLED=${MODEL_FALLBACK_ENABLED:-false}
                    depends_on:
                      postgres:
                        condition: service_healthy
                    healthcheck:
                      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health/liveness"]
                      interval: 30s
                      timeout: 5s
                      retries: 3
                      start_period: 30s
                    restart: unless-stopped

                  postgres:
                    image: postgres:17-alpine
                    environment:
                      - POSTGRES_DB=${DB_NAME:-javaclaw}
                      - POSTGRES_USER=${DB_USERNAME:-javaclaw}
                      - POSTGRES_PASSWORD=${DB_PASSWORD:-javaclaw}
                    volumes:
                      - pgdata:/var/lib/postgresql/data
                    healthcheck:
                      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-javaclaw}"]
                      interval: 10s
                      timeout: 5s
                      retries: 5
                    restart: unless-stopped

                volumes:
                  pgdata:
                """;
    }

    public String generateEnvExample() {
        Map<String, String> vars = new TreeMap<>();
        vars.put("PORT", "8080");
        vars.put("DB_HOST", "localhost");
        vars.put("DB_PORT", "5432");
        vars.put("DB_NAME", "javaclaw");
        vars.put("DB_USERNAME", "javaclaw");
        vars.put("DB_PASSWORD", "javaclaw");
        vars.put("OPENROUTER_API_KEY", "sk-or-v1-your-key-here");
        vars.put("OPENAI_BASE_URL", "https://openrouter.ai/api/v1");
        vars.put("CHAT_MODEL", "anthropic/claude-sonnet-4-20250514");
        vars.put("ADMIN_PASSWORD", "admin");
        vars.put("USER_PASSWORD", "user");
        vars.put("WORKSPACE_DIR", ".");
        vars.put("THINKING_ENABLED", "false");
        vars.put("THINKING_BUDGET_TOKENS", "10000");
        vars.put("MODEL_FALLBACK_ENABLED", "false");
        vars.put("MODEL_FALLBACK_MODELS", "");
        vars.put("MODEL_FALLBACK_MAX_RETRIES", "2");

        var sb = new StringBuilder();
        sb.append("# JavaClaw Environment Variables\n");
        sb.append("# Generated by ConfigGenerator — copy to .env and customize\n\n");

        sb.append("# === Required ===\n");
        sb.append("OPENROUTER_API_KEY=sk-or-v1-your-key-here\n\n");

        sb.append("# === Database ===\n");
        sb.append("DB_HOST=localhost\n");
        sb.append("DB_PORT=5432\n");
        sb.append("DB_NAME=javaclaw\n");
        sb.append("DB_USERNAME=javaclaw\n");
        sb.append("DB_PASSWORD=javaclaw\n\n");

        sb.append("# === Server ===\n");
        sb.append("PORT=8080\n");
        sb.append("WORKSPACE_DIR=.\n\n");

        sb.append("# === Auth ===\n");
        sb.append("ADMIN_PASSWORD=admin\n");
        sb.append("USER_PASSWORD=user\n\n");

        sb.append("# === AI Model ===\n");
        sb.append("OPENAI_BASE_URL=https://openrouter.ai/api/v1\n");
        sb.append("CHAT_MODEL=anthropic/claude-sonnet-4-20250514\n");
        sb.append("THINKING_ENABLED=false\n");
        sb.append("THINKING_BUDGET_TOKENS=10000\n\n");

        sb.append("# === Fallback ===\n");
        sb.append("MODEL_FALLBACK_ENABLED=false\n");
        sb.append("MODEL_FALLBACK_MODELS=\n");
        sb.append("MODEL_FALLBACK_MAX_RETRIES=2\n");

        return sb.toString();
    }

    public Map<String, String> getEnvironmentVariables() {
        Map<String, String> vars = new TreeMap<>();
        vars.put("PORT", "8080");
        vars.put("DB_HOST", "localhost");
        vars.put("DB_PORT", "5432");
        vars.put("DB_NAME", "javaclaw");
        vars.put("DB_USERNAME", "javaclaw");
        vars.put("DB_PASSWORD", "javaclaw");
        vars.put("OPENROUTER_API_KEY", "sk-or-v1-your-key-here");
        vars.put("OPENAI_BASE_URL", "https://openrouter.ai/api/v1");
        vars.put("CHAT_MODEL", "anthropic/claude-sonnet-4-20250514");
        vars.put("ADMIN_PASSWORD", "admin");
        vars.put("USER_PASSWORD", "user");
        vars.put("WORKSPACE_DIR", ".");
        vars.put("THINKING_ENABLED", "false");
        vars.put("THINKING_BUDGET_TOKENS", "10000");
        vars.put("MODEL_FALLBACK_ENABLED", "false");
        vars.put("MODEL_FALLBACK_MODELS", "");
        vars.put("MODEL_FALLBACK_MAX_RETRIES", "2");
        return vars;
    }
}
